config/routes.rb
Rails.application.routes.draw do
  get 'profile/:id/edit', to: "profile#edit"

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  post "/logout", to: "sessions#destroy"

  get "/users/:id/profile", to: "users#profile"
  
  resources :reservations, only: [:index,:destroy] do
    member do
      post 'confirm'
      post 'back'
    end
    collection do
      post 'confirm'
      post 'back'
    end
  end

  post 'reservations/create', to: "reservations#create"

  get '/reservations/:id/confirm', to: "reservations#create"

  post '/reservations/:id/back', to: "reservations#back"

  resources :rooms do
    collection do
      get 'own'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users, only:[:index,:new,:show,:edit,:profile]
  resources :profile, only:[:edit]

  resources :users do
    get 'profile', on: :member
  end
  resources :static_pages do
    resources :users , only: [:home]
  end
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: {maximum: 50}

    VALID_EMAIL_REGEX = /\A[\w+\.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length:{maximum: 255},
    format: {with: VALID_EMAIL_REGEX },
    uniqueness: true
    has_secure_password

    validates :password, presence: true, length: { minimum:6 },
                        allow_nil: true

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    mount_uploader :post_image, ImageUploader

    has_many :rooms, dependent: :destroy
    has_many :reservations, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :correct_user, only: [:edit, :update]

    def show
        @user = User.find(params[:id])
    end

    def profile
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
         log_in @user
         flash.now[:danger] = "新規登録に成功しました"
         redirect_to @user
        else
         flash.now[:danger] = "新規登録に失敗しました"
         render 'new', status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end
  
    def update
        @user = User.find(params[:id])
        if  @user.update(user_params)
            flash.now[:danger] = "編集に成功しました"
            redirect_to @user
        else
            flash.now[:danger] = "編集に失敗しました"
            render 'edit'
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :post_image, :introduction)
    end

    def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user? @user
    end

end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/account.htnl.erb
<%= render "shared/main" %>
<h2>アカウント</h2>
<%= @user.name %>
<p>*********</p>

app/views/users/edit.html.erb
<h1>アカウント編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :確認用パスワード %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "保存", class: "btn btn-primary" %>
    <% end %>

    
  </div>
</div>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render "shared/error", obj:@user %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
        

        <%= f.label :ユーザー名 %>
        <%= f.text_field :name, class: 'form-control' %>
  
        <%= f.label :メールアドレス %>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.label :パスワード %>
        <%= f.password_field :password, class: 'form-control' %>
  
        <%= f.label :確認用パスワード %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "新しいアカウントを作成", class: "btn btn-primary" %>

      <p>アカウントをお持ちの方はログイン <%= link_to "ログイン", login_path %></p>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<%= render "shared/main" %>
<h2>プロフィール</h2>
<h2>編集</h2>

    <ul><% if @user.post_image.blank? %>
    <li><%= image_tag "/assets/default.png" %></li>
    <li><%= @user.name %></li>
    <li><%= @user.introduction %></li>
    <p><%= link_to '編集', [:edit_profile] %></p>
    <% else %>
       <li><%= image_tag @user.post_image.url %></li>
       <li><%= @user.name %></li>
       <li><%= @user.introduction %></li>
       <p><%= link_to '編集', [:edit_profile] %></p>
    <% end %>
    </ul>

app/views/users/show.html.erb
<%= render "shared/main" %>
<h2>アカウント</h2>
<h2>編集</h2>
<%= @user.email %>
<p>*********</p>

<%= link_to '編集', edit_user_path(@user) %>