config/routes.rb
Rails.application.routes.draw do
  get 'profile/:id/edit', to: "profile#edit"

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  post "/logout", to: "sessions#destroy"

  get "/users/:id/profile", to: "users#profile"
  
  resources :reservations, only: [:index,:destroy] do
    member do
      post 'confirm'
      post 'back'
    end
    collection do
      post 'confirm'
      post 'back'
    end
  end

  post 'reservations/create', to: "reservations#create"

  get '/reservations/:id/confirm', to: "reservations#create"

  post '/reservations/:id/back', to: "reservations#back"

  resources :rooms do
    collection do
      get 'own'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users, only:[:index,:new,:show,:edit,:profile]
  resources :profile, only:[:edit]

  resources :users do
    get 'profile', on: :member
  end
  resources :static_pages do
    resources :users , only: [:home]
  end
end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<ul>
   <% obj.errors.full_messages.each do |message| %>
     <li><%= message %></li>
     </ul>
   <% end %>
 <% end %>

app/views/shared/_main.html.erb
<main class="account">
  <section class="a_container">
    <h2>設定</h2>
    <div class="a_div">
      <ul class="a_ul">
        <li><%= link_to "アカウント", user_path %></li>
        <li><%= link_to "プロフィール", profile_user_path(@user.id) %></li>
      </ul>
    </div>
  </section>
</main>