config/routes.rb
Rails.application.routes.draw do
  get 'profile/:id/edit', to: "profile#edit"

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  post "/logout", to: "sessions#destroy"

  get "/users/:id/profile", to: "users#profile"
  
  resources :reservations, only: [:index,:destroy] do
    member do
      post 'confirm'
      post 'back'
    end
    collection do
      post 'confirm'
      post 'back'
    end
  end

  post 'reservations/create', to: "reservations#create"

  get '/reservations/:id/confirm', to: "reservations#create"

  post '/reservations/:id/back', to: "reservations#back"

  resources :rooms do
    collection do
      get 'own'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users, only:[:index,:new,:show,:edit,:profile]
  resources :profile, only:[:edit]

  resources :users do
    get 'profile', on: :member
  end
  resources :static_pages do
    resources :users , only: [:home]
  end
end

app/models/room.rb
class Room < ApplicationRecord
    validates :room_name, presence: true
    validates :room_intro, presence: true
    validates :fee_p_d, presence: true, numericality: { only_integer: true }, format: { with: /\A[0-9\d]+\z/ }
    validates :address, presence: true
    validates :user_id, presence: true
    mount_uploader :room_image, ImageUploader

    has_many :reservations, dependent: :destroy
    belongs_to :users, optional:true

    def self.ransackable_attributes(auth_object = nil)
        ["address", "created_at", "fee_p_d", "id", "room_image", "room_intro", "room_name", "updated_at", "user_id"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["user"]
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  

  def index
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
    if @q_home
      @rooms = @q_home.result(distinct: true)
      if @q_home && @q
        @rooms = @q_home&&@q.result(distinct: true)
      end
    end
  end

  def own
    @rooms = Room.where(user_id: current_user.id)
  end

  def new
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "新規登録しました"
      redirect_to rooms_path
    else
      flash[:notice] = "新規登録に失敗しました"
      render 'new'
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  private

  def room_params
    params.require(:room).permit!
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_search.html.erb
<%= search_form_for @q_home,url: rooms_path do |f| %>
    <%= f.search_field :address_cont, class: 'form-control', placeholder: 'エリア名を入力' %>
    <%= f.submit '検索', class: 'btn btn-primary' %>
 <% end %>

app/views/rooms/index.html.erb
<div>
  <%= search_form_for @q_home,url: rooms_path do |f| %>
    <%= f.search_field :address_cont, class: 'form-control', placeholder: 'エリア名を入力' %>
  <%= search_form_for @q,url: rooms_path do |f| %>
    <%= f.search_field :room_name_or_room_intro_cont, class: 'form-control', placeholder: 'キーワードを入力' %>
    <%= f.submit '検索', class: 'btn btn-primary' %>
  <% end %>
  <% end %>
</div>

<div>
  <p><%= "#{@rooms.count}件が見つかりました。" %></p>
</div>

 <h3>登録一覧</h3>

 <table>
   <thead>
     <tr>
       <th>施設名</th>
       <th>施設詳細</th>
       <th>料金</th>
       <th>施設画像</th>
       <th>住所</th>
       <th>投稿日時</th>
     </tr>
   </thead>
 
   <tbody>
     <% @rooms.each do |room| %>
       <tr>
         <td><%= room.room_name %></td>
         <td><%= room.room_intro %></td>
         <td><%= room.fee_p_d %></td>
         <td>
         <% if room.room_image.blank? %>
          <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
         <% else %>
          <%= image_tag room.room_image.url %>
         <% end %>
         </td>
         <td><%= room.address %></td>
         <td><%= room.created_at.strftime("%Y年%m月%d日") %></td>
         <td><%= link_to "詳細はこちらから", room, method: :get  %></td>
       </tr>
     <% end %>
   </tbody>
 </table>

app/views/rooms/new.html.erb
<h2>新規登録</h2>

<%= render "shared/error", obj:@room %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @room do |f| %>
        

        <%= f.label :施設名 %>
        <%= f.text_field :room_name, class: 'form-control' %>

        <% if @room.errors.include?(:room_name) %>
        <% @room = @room.errors.full_messages_for(:room_name).first %>
        <% end %>
  
        <%= f.label :施設詳細 %>
        <%= f.text_area :room_intro, class: 'form-control' %>
  
        <%= f.label :料金 %>
        <%= f.text_field :fee_p_d, class: 'form-control' %>
  
        <%= f.label :住所 %>
        <%= f.text_field :address, class: 'form-control' %>

        <%= f.label :施設画像 %>
      <%= f.file_field :room_image, class: 'form-control' %>
      <%= f.hidden_field :room_image_cache %>

      <%= f.hidden_field :user_id, class: 'form-control' %>

      <%= f.submit "保存", class: "btn btn-primary" %>

      <%= link_to "キャンセル", :back %>

    <% end %>
  </div>
</div>

app/views/rooms/own.html.erb
<h3>登録一覧</h3>

 <table>
   <thead>
     <tr>
       <th>施設名</th>
       <th>施設詳細</th>
       <th>料金</th>
       <th>施設画像</th>
       <th>住所</th>
       <th>投稿日時</th>
     </tr>
   </thead>
 
   <tbody>
     <% @rooms.each do |room| %>
       <tr>
         <td><%= link_to room.room_name, room, method: :get %></td>
         <td><%= room.room_intro %></td>
         <td><%= room.fee_p_d %></td>
         <td>
         <% if room.room_image.blank? %>
          <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
         <% else %>
          <%= image_tag room.room_image.url %>
         <% end %>
         </td>
         <td><%= room.address %></td>
         <td><%= room.created_at.strftime("%Y年%m月%d日") %></td>
       </tr>
     <% end %>
   </tbody>
 </table>

app/views/rooms/show.html.erb
<body class="error_message_margin">
<h3>登録詳細</h3>
 
 <table>
   <thead>
     <tr>
       <th>施設名</th>
       <th>施設詳細</th>
       <th>料金</th>
       <th>住所</th>
       <th>施設画像</th>
     </tr>
   </thead>
 
   <tbody>
       <tr>
         <td><%= @room.room_name %></td>
         <td><%= @room.room_intro %></td>
         <td><%= @room.fee_p_d %></td>
         <td><%= @room.address %></td>
         <td>
         <% if @room.room_image.blank? %>
          <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
         <% else %>
          <%= image_tag @room.room_image.url %>
         <% end %>
         </td>
       </tr>
   </tbody>
 </table>

 <div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @reservation, method: :post, url: confirm_reservation_path(:id)  do |f| %> 

      <%= f.label :チェックイン %>
      <%= f.date_field :checkin, class: 'form-control' %>
  
      <%= f.label :チェックアウト %>
      <%= f.date_field :checkout, class: 'form-control' %>
  
      <%= f.label :人数 %>
      <%= f.text_field :num_o_p, class: 'form-control' %>

      <% if current_user.blank? %>

      <%= link_to 'ログインする', login_path %>  
      
      <% else %>

      <%= f.hidden_field :user_id, :value => current_user.id %>

      <%= f.hidden_field :room_id, :value => @room.id %>

      <%= f.submit "予約する", class: "btn btn-primary" %>

      <% if @reservation.errors.any? %>
      <ul>
      <% @reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      </ul>
      <% end %>
      <% end %>

      <% end %>

    <% end %>
  </div>
</div>

 <%= link_to "戻る", :back %>
 
 </body>