config/routes.rb
Rails.application.routes.draw do
  get 'profile/:id/edit', to: "profile#edit"

  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  post "/logout", to: "sessions#destroy"

  get "/users/:id/profile", to: "users#profile"
  
  resources :reservations, only: [:index,:destroy] do
    member do
      post 'confirm'
      post 'back'
    end
    collection do
      post 'confirm'
      post 'back'
    end
  end

  post 'reservations/create', to: "reservations#create"

  get '/reservations/:id/confirm', to: "reservations#create"

  post '/reservations/:id/back', to: "reservations#back"

  resources :rooms do
    collection do
      get 'own'
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  resources :users, only:[:index,:new,:show,:edit,:profile]
  resources :profile, only:[:edit]

  resources :users do
    get 'profile', on: :member
  end
  resources :static_pages do
    resources :users , only: [:home]
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <a><%= link_to "Potepan Share", root_path, id: "logo" %></a>
    <nav class="navbar-nav">
      <ul class="nav navbar-right">
      <% if logged_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <%= image_tag current_user.post_image.url, size: "30x30" %>
        <%= current_user.name %>
        <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
        <li><%= link_to "施設の新規登録", new_room_path %></li>
          <li class="divider"></li>
          <li><%= link_to "予約済み一覧", reservations_path %></li>
          <li><%= link_to "登録済み一覧", own_rooms_path %></li>
          <li><%= link_to "アカウント設定", current_user %></li>
          <li class="divider"></li>
          <li>
            <%= button_to "ログアウト", logout_path, data: { turbo_method: :delete} %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "ログイン", login_path %></li>
      <li><%= link_to "新規登録", signup_path %></li>
    <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "custom", :media => "all" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
      <%= yield %>
    </div>
  </body>
</html>